name: CICD for quantum testing
on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - remote-trigger

jobs:
    main_job:
        runs-on: ubuntu-20.04
        permissions:
            contents: "read"

        steps:
            - name: Test
              run: |
                echo "This is a test github action"
                echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

            - name: Inform quantum #TODO
              uses: fjogeleit/http-request-action@v1
              with:
                url: 'https://api.breu.ngrok.io/providers/github/cicd-result'
                method: 'POST'
                customHeaders: '{"Content-Type": "application/json"}'
                # customHeaders: '{"Content-Type": "application/json", "X-API-KEY": "${{secrets.QUANTUM_API_KEY}}"}'
                data: '{"result": "success", "branch": "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"}'
